### ISSUE TITLE
ない画像を表示しようとしてる?

### ISSUE THREAD

**Issue by sender1999** [KissLeaRon/lan_chatapp#10]
画像の連投バグは直ってそうだけど、初期化された画像データをそのあと表示しようとしてる?

**Comment by sender1999** [comment]
![Screenshot from 2022-05-11 11-17-40](https://user-images.githubusercontent.com/5279072/167755603-357569c5-c90f-4aac-af82-ca43811b51bc.png)

**Comment by KissLeaRon** [comment]
にゃ～ん

それも見たとおもうんですよね
検証する>consoleから見たら `"img_base64" : "data:"` となっている気がするので
その例外処理は済んだと思ってたんですが、そちらからは何が"img_base64"に格納されていますか?

**Comment by sender1999** [comment]
正しいところは
`<img src="data:image/png;base64,iVBOR~~~~~`
で変なところは
`<img src="data:application/octet-stream;base64,">`
こうなってるから単に、画像ないのにimgエレメント入れてるだけ説

**Comment by sender1999** [comment]
直した

**Comment by sender1999** [comment]
直したのでブランチ作ってマージします〜

**Comment by sender1999** [comment]
imgエレメント入れるifの中をパターン一致に変えたら直りました。
